/**
 * TIMELINE VIEW COMPONENT
 *
 * Primary interface for the Outreach Window Planner.
 * Simplified, Cursor-style layout with consolidated controls.
 */

"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  ChevronDown,
  ChevronUp,
  Clock,
  CheckCircle2,
  AlertCircle,
  XCircle,
  Copy,
  Share2,
  Calendar,
  ChevronsUpDown,
  BellPlus,
} from "lucide-react";

import type { TemporalSignal } from "@/lib/temporal/types";
import type { OutreachWindow, WindowType } from "@/lib/temporal/aggregate";
import type { AlertDraft } from "@/lib/alerts/types";

/**
 * Window type styling configuration.
 */
const WINDOW_STYLES: Record<
  WindowType,
  {
    bg: string;
    border: string;
    label: string;
    description: string;
    icon: React.ElementType;
  }
> = {
  safer: {
    bg: "bg-emerald-50 dark:bg-emerald-950/30",
    border: "border-emerald-200 dark:border-emerald-800",
    label: "Safer",
    description: "Good conditions for outreach",
    icon: CheckCircle2,
  },
  caution: {
    bg: "bg-amber-50 dark:bg-amber-950/30",
    border: "border-amber-200 dark:border-amber-800",
    label: "Caution",
    description: "Moderate activity expected",
    icon: AlertCircle,
  },
  highDisruption: {
    bg: "bg-stone-100 dark:bg-stone-900/50",
    border: "border-stone-300 dark:border-stone-700",
    label: "Disruption",
    description: "Consider alternative timing",
    icon: XCircle,
  },
};

interface TimelineViewProps {
  windows: OutreachWindow[];
  signals: TemporalSignal[];
  selectedWindowId?: string;
  onWindowSelect: (windowId: string | undefined) => void;
  scenarioMode: boolean;
  onScenarioModeChange: (enabled: boolean) => void;
  filterType?: string | null;
  onFilterChange?: (filter: string | null) => void;
  onCreateAlert?: (draft: AlertDraft) => void;
}

export function TimelineView({
  windows,
  signals,
  selectedWindowId,
  onWindowSelect,
  scenarioMode,
  onScenarioModeChange,
  filterType,
  onFilterChange,
  onCreateAlert,
}: TimelineViewProps) {
  const [expandedWindows, setExpandedWindows] = useState<Set<string>>(
    new Set()
  );
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Group windows by day for better visualization
  const windowsByDay = groupWindowsByDay(windows);

  const toggleExpanded = (windowId: string) => {
    const newExpanded = new Set(expandedWindows);
    if (newExpanded.has(windowId)) {
      newExpanded.delete(windowId);
    } else {
      newExpanded.add(windowId);
    }
    setExpandedWindows(newExpanded);
  };

  // Expand all windows
  const expandAll = () => {
    setExpandedWindows(new Set(windows.map((w) => w.id)));
  };

  // Collapse all windows
  const collapseAll = () => {
    setExpandedWindows(new Set());
  };

  // Find signals for a window
  const getWindowSignals = (window: OutreachWindow): TemporalSignal[] => {
    return signals.filter((s) => window.driverSignalIds.includes(s.id));
  };

  // Copy window details to clipboard
  const copyWindowDetails = (window: OutreachWindow) => {
    const style = WINDOW_STYLES[window.windowType];
    const text = `
Outreach Window: ${style.label}
Time: ${formatTimeRange(window.timeRange)}
Status: ${style.description}

${window.plainLanguageWhy}

Suggested Approach:
${window.suggestedApproach}

---
Generated by Outreach Window Planner (simulated data)
    `.trim();

    navigator.clipboard.writeText(text);
    setCopiedId(window.id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Add to calendar (generates ICS-like data for demo)
  const addToCalendar = (outreachWindow: OutreachWindow) => {
    const style = WINDOW_STYLES[outreachWindow.windowType];
    const start = new Date(outreachWindow.timeRange.start);
    const end = new Date(outreachWindow.timeRange.end);

    // Create a Google Calendar URL for demo
    const calendarUrl = new URL("https://calendar.google.com/calendar/render");
    calendarUrl.searchParams.set("action", "TEMPLATE");
    calendarUrl.searchParams.set("text", `Outreach Window: ${style.label}`);
    calendarUrl.searchParams.set(
      "details",
      `${outreachWindow.plainLanguageWhy}\n\nSuggested Approach:\n${outreachWindow.suggestedApproach}\n\n(Generated by Outreach Window Planner - simulated data)`
    );
    calendarUrl.searchParams.set(
      "dates",
      `${formatCalendarDate(start)}/${formatCalendarDate(end)}`
    );
    calendarUrl.searchParams.set("location", "Koreatown, Los Angeles");

    globalThis.window.open(calendarUrl.toString(), "_blank");
  };

  // Share window (Web Share API)
  const shareWindow = async (window: OutreachWindow) => {
    const style = WINDOW_STYLES[window.windowType];
    const shareData = {
      title: `Outreach Window: ${style.label}`,
      text: `${formatTimeRange(window.timeRange)} - ${window.plainLanguageWhy}`,
      url:
        typeof globalThis.window !== "undefined"
          ? globalThis.window.location.href
          : "",
    };

    if (navigator.share && navigator.canShare(shareData)) {
      await navigator.share(shareData);
    } else {
      // Fallback: copy to clipboard
      copyWindowDetails(window);
    }
  };

  // Create alert from window
  const createAlertFromWindow = (window: OutreachWindow) => {
    if (!onCreateAlert) return;

    const style = WINDOW_STYLES[window.windowType];
    onCreateAlert({
      title: `Outreach: ${style.label} window`,
      notes: `${window.plainLanguageWhy}\n\nSuggested approach:\n${window.suggestedApproach}`,
      timeRange: window.timeRange,
      source: "timeline",
      relatedIds: {
        windowId: window.id,
        signalIds: window.driverSignalIds,
      },
    });
  };

  return (
    <div className="p-6 space-y-4">
      {/* Compact Toolbar */}
      <div className="flex items-center justify-between gap-4">
        <p className="text-sm text-muted-foreground">
          {windows.length} window{windows.length !== 1 ? "s" : ""}
        </p>

        <div className="flex items-center gap-2">
          {/* Filter Dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="h-8 gap-1.5 text-xs"
              >
                {filterType
                  ? WINDOW_STYLES[filterType as WindowType]?.label
                  : "All types"}
                <ChevronDown className="h-3 w-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => onFilterChange?.(null)}>
                All types
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              {(Object.keys(WINDOW_STYLES) as WindowType[]).map((type) => {
                const style = WINDOW_STYLES[type];
                const Icon = style.icon;
                return (
                  <DropdownMenuItem
                    key={type}
                    onClick={() => onFilterChange?.(type)}
                  >
                    <Icon className="h-3.5 w-3.5 mr-2" />
                    {style.label}
                  </DropdownMenuItem>
                );
              })}
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Expand/Collapse */}
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="h-8 w-8 p-0"
                onClick={expandedWindows.size > 0 ? collapseAll : expandAll}
              >
                <ChevronsUpDown className="h-3.5 w-3.5" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              {expandedWindows.size > 0 ? "Collapse all" : "Expand all"}
            </TooltipContent>
          </Tooltip>

          {/* What-if Toggle */}
          <div className="flex items-center gap-2 ml-2">
            <Switch
              id="scenario-mode"
              checked={scenarioMode}
              onCheckedChange={onScenarioModeChange}
              className="scale-90"
            />
            <Tooltip>
              <TooltipTrigger asChild>
                <label
                  htmlFor="scenario-mode"
                  className="text-xs text-muted-foreground cursor-pointer"
                >
                  What-if
                </label>
              </TooltipTrigger>
              <TooltipContent>
                Simulate reduced outreach capacity for planning
              </TooltipContent>
            </Tooltip>
          </div>
        </div>
      </div>

      {/* What-if Mode Notice */}
      {scenarioMode && (
        <div className="bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 rounded-md px-3 py-2">
          <p className="text-xs text-amber-800 dark:text-amber-200">
            <strong>What-if mode:</strong> Showing speculative adjustments. Use
            for planning exercises only.
          </p>
        </div>
      )}

      {/* Timeline */}
      <div className="space-y-6">
        {Object.entries(windowsByDay).map(([dayKey, dayWindows]) => (
          <div key={dayKey} className="space-y-3">
            {/* Day Header */}
            <div className="sticky top-0 bg-background/95 backdrop-blur-sm py-2 z-10">
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <h3 className="text-sm font-medium">
                  {formatDayHeader(dayKey)}
                </h3>
                <Badge variant="outline" className="text-xs">
                  {dayWindows.length} window{dayWindows.length !== 1 ? "s" : ""}
                </Badge>
              </div>
            </div>

            {/* Windows for this day */}
            <div className="space-y-2 pl-4 border-l-2 border-muted">
              {dayWindows.map((window) => {
                const isExpanded = expandedWindows.has(window.id);
                const isSelected = selectedWindowId === window.id;
                const windowSignals = getWindowSignals(window);
                const style = WINDOW_STYLES[window.windowType];
                const Icon = style.icon;

                return (
                  <Card
                    key={window.id}
                    className={`
                      ${style.bg} ${style.border}
                      ${isSelected ? "ring-2 ring-ring" : ""}
                      transition-all cursor-pointer hover:shadow-md
                    `}
                    onClick={() =>
                      onWindowSelect(isSelected ? undefined : window.id)
                    }
                  >
                    <CardHeader className="py-3 px-4">
                      <div className="flex items-start justify-between gap-2">
                        <div className="space-y-1 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <Icon className="h-4 w-4 text-muted-foreground" />
                            <Badge
                              variant="outline"
                              className="text-xs font-normal"
                            >
                              {formatTimeRange(window.timeRange)}
                            </Badge>
                            <Badge
                              variant={
                                window.windowType === "safer"
                                  ? "default"
                                  : "secondary"
                              }
                              className="text-xs"
                            >
                              {style.label}
                            </Badge>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Badge variant="outline" className="text-xs">
                                  {window.confidenceSummary}
                                </Badge>
                              </TooltipTrigger>
                              <TooltipContent>
                                <p>Data confidence level</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <CardTitle className="text-sm font-medium">
                            {style.description}
                          </CardTitle>
                        </div>
                        <div className="flex items-center gap-1">
                          {/* Quick Actions */}
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  copyWindowDetails(window);
                                }}
                              >
                                <Copy
                                  className={`h-4 w-4 ${
                                    copiedId === window.id
                                      ? "text-green-500"
                                      : ""
                                  }`}
                                />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                              {copiedId === window.id
                                ? "Copied!"
                                : "Copy details"}
                            </TooltipContent>
                          </Tooltip>

                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  addToCalendar(window);
                                }}
                              >
                                <Calendar className="h-4 w-4" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Add to calendar</TooltipContent>
                          </Tooltip>

                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  shareWindow(window);
                                }}
                              >
                                <Share2 className="h-4 w-4" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Share</TooltipContent>
                          </Tooltip>

                          {onCreateAlert && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    createAlertFromWindow(window);
                                  }}
                                >
                                  <BellPlus className="h-4 w-4" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>Create alert</TooltipContent>
                            </Tooltip>
                          )}

                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={(e) => {
                              e.stopPropagation();
                              toggleExpanded(window.id);
                            }}
                          >
                            {isExpanded ? (
                              <>
                                <ChevronUp className="h-4 w-4 mr-1" />
                                Less
                              </>
                            ) : (
                              <>
                                <ChevronDown className="h-4 w-4 mr-1" />
                                More
                              </>
                            )}
                          </Button>
                        </div>
                      </div>
                    </CardHeader>

                    {/* Expanded Content */}
                    {isExpanded && (
                      <CardContent className="pt-0 px-4 pb-4 space-y-3">
                        <div className="border-t" />

                        {/* Why explanation */}
                        <div>
                          <p className="text-sm text-muted-foreground">
                            {window.plainLanguageWhy}
                          </p>
                        </div>

                        {/* Suggested approach */}
                        <div className="bg-background/50 rounded-md p-3">
                          <p className="text-xs font-medium mb-1">
                            Suggested Approach
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {window.suggestedApproach}
                          </p>
                        </div>

                        {/* Contributing signals */}
                        {windowSignals.length > 0 && (
                          <div>
                            <p className="text-xs font-medium mb-2">
                              Contributing Signals ({windowSignals.length})
                            </p>
                            <div className="space-y-1">
                              {windowSignals.slice(0, 3).map((signal) => (
                                <div
                                  key={signal.id}
                                  className="text-xs text-muted-foreground flex items-center gap-2"
                                >
                                  <Badge
                                    variant="outline"
                                    className="text-xs py-0"
                                  >
                                    {signal.impactLevel}
                                  </Badge>
                                  <span className="truncate">
                                    {signal.description}
                                  </span>
                                </div>
                              ))}
                              {windowSignals.length > 3 && (
                                <p className="text-xs text-muted-foreground">
                                  +{windowSignals.length - 3} more signals
                                </p>
                              )}
                            </div>
                          </div>
                        )}
                      </CardContent>
                    )}
                  </Card>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Empty state */}
      {windows.length === 0 && (
        <div className="py-12 text-center">
          <p className="text-sm text-muted-foreground">
            {filterType
              ? `No ${WINDOW_STYLES[
                  filterType as WindowType
                ]?.label.toLowerCase()} windows found.`
              : "No windows for this period."}
          </p>
          {filterType && (
            <Button
              variant="link"
              size="sm"
              onClick={() => onFilterChange?.(null)}
              className="mt-1"
            >
              Clear filter
            </Button>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Group windows by day for organized display.
 */
function groupWindowsByDay(
  windows: OutreachWindow[]
): Record<string, OutreachWindow[]> {
  const groups: Record<string, OutreachWindow[]> = {};

  for (const window of windows) {
    const startDate = new Date(window.timeRange.start);
    const dayKey = startDate.toISOString().split("T")[0];

    if (!groups[dayKey]) {
      groups[dayKey] = [];
    }
    groups[dayKey].push(window);
  }

  return groups;
}

/**
 * Format a day key into a human-readable header.
 */
function formatDayHeader(dayKey: string): string {
  const date = new Date(dayKey);
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  if (date.toDateString() === today.toDateString()) {
    return "Today";
  }
  if (date.toDateString() === tomorrow.toDateString()) {
    return "Tomorrow";
  }

  return date.toLocaleDateString("en-US", {
    weekday: "long",
    month: "short",
    day: "numeric",
  });
}

/**
 * Format a time range for display.
 */
function formatTimeRange(timeRange: { start: string; end: string }): string {
  const start = new Date(timeRange.start);
  const end = new Date(timeRange.end);

  const startTime = start.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });
  const endTime = end.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });

  // If same day
  if (start.toDateString() === end.toDateString()) {
    return `${startTime} - ${endTime}`;
  }

  // Multi-day
  return `${startTime} - ${end.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  })} ${endTime}`;
}

/**
 * Format date for Google Calendar URL.
 */
function formatCalendarDate(date: Date): string {
  return date.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
}
