/**
 * TIMELINE VIEW COMPONENT
 *
 * The PRIMARY interface for the Outreach Window Planner.
 * Displays outreach windows in a vertical timeline format.
 *
 * DESIGN PHILOSOPHY:
 * - Time is the dominant dimension (vertical axis = time progression)
 * - Windows are color-coded by type (safer/caution/high disruption)
 * - Colors are intentionally muted to avoid alarming visuals
 * - Plain-language explanations are always visible
 *
 * ACCESSIBILITY:
 * - Uses semantic HTML for screen readers
 * - Color is not the only indicator (text labels included)
 * - Interactive elements have clear focus states
 * - WCAG 2.1 AA compliant color contrast
 */

"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Filter,
  ChevronDown,
  ChevronUp,
  Clock,
  CheckCircle2,
  AlertCircle,
  XCircle,
  Copy,
  Share2,
  Calendar,
} from "lucide-react";

import type { TemporalSignal } from "@/lib/temporal/types";
import type { OutreachWindow, WindowType } from "@/lib/temporal/aggregate";

/**
 * Window type styling configuration.
 * Colors are intentionally muted for calm, operational aesthetic.
 */
const WINDOW_STYLES: Record<
  WindowType,
  {
    bg: string;
    border: string;
    label: string;
    description: string;
    icon: React.ElementType;
  }
> = {
  safer: {
    bg: "bg-emerald-50 dark:bg-emerald-950/30",
    border: "border-emerald-200 dark:border-emerald-800",
    label: "Safer Window",
    description: "Good conditions for outreach",
    icon: CheckCircle2,
  },
  caution: {
    bg: "bg-amber-50 dark:bg-amber-950/30",
    border: "border-amber-200 dark:border-amber-800",
    label: "Caution",
    description: "Moderate activity expected",
    icon: AlertCircle,
  },
  highDisruption: {
    bg: "bg-stone-100 dark:bg-stone-900/50",
    border: "border-stone-300 dark:border-stone-700",
    label: "High Disruption",
    description: "Consider alternative timing",
    icon: XCircle,
  },
};

interface TimelineViewProps {
  windows: OutreachWindow[];
  signals: TemporalSignal[];
  selectedWindowId?: string;
  onWindowSelect: (windowId: string | undefined) => void;
  scenarioMode: boolean;
  onScenarioModeChange: (enabled: boolean) => void;
  filterType?: string | null;
  onFilterChange?: (filter: string | null) => void;
}

export function TimelineView({
  windows,
  signals,
  selectedWindowId,
  onWindowSelect,
  scenarioMode,
  onScenarioModeChange,
  filterType,
  onFilterChange,
}: TimelineViewProps) {
  const [expandedWindows, setExpandedWindows] = useState<Set<string>>(
    new Set()
  );
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Group windows by day for better visualization
  const windowsByDay = groupWindowsByDay(windows);

  const toggleExpanded = (windowId: string) => {
    const newExpanded = new Set(expandedWindows);
    if (newExpanded.has(windowId)) {
      newExpanded.delete(windowId);
    } else {
      newExpanded.add(windowId);
    }
    setExpandedWindows(newExpanded);
  };

  // Expand all windows
  const expandAll = () => {
    setExpandedWindows(new Set(windows.map((w) => w.id)));
  };

  // Collapse all windows
  const collapseAll = () => {
    setExpandedWindows(new Set());
  };

  // Find signals for a window
  const getWindowSignals = (window: OutreachWindow): TemporalSignal[] => {
    return signals.filter((s) => window.driverSignalIds.includes(s.id));
  };

  // Copy window details to clipboard
  const copyWindowDetails = (window: OutreachWindow) => {
    const style = WINDOW_STYLES[window.windowType];
    const text = `
Outreach Window: ${style.label}
Time: ${formatTimeRange(window.timeRange)}
Status: ${style.description}

${window.plainLanguageWhy}

Suggested Approach:
${window.suggestedApproach}

---
Generated by Outreach Window Planner (simulated data)
    `.trim();

    navigator.clipboard.writeText(text);
    setCopiedId(window.id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Add to calendar (generates ICS-like data for demo)
  const addToCalendar = (window: OutreachWindow) => {
    const style = WINDOW_STYLES[window.windowType];
    const start = new Date(window.timeRange.start);
    const end = new Date(window.timeRange.end);

    // Create a Google Calendar URL for demo
    const calendarUrl = new URL("https://calendar.google.com/calendar/render");
    calendarUrl.searchParams.set("action", "TEMPLATE");
    calendarUrl.searchParams.set("text", `Outreach Window: ${style.label}`);
    calendarUrl.searchParams.set(
      "details",
      `${window.plainLanguageWhy}\n\nSuggested Approach:\n${window.suggestedApproach}\n\n(Generated by Outreach Window Planner - simulated data)`
    );
    calendarUrl.searchParams.set(
      "dates",
      `${formatCalendarDate(start)}/${formatCalendarDate(end)}`
    );
    calendarUrl.searchParams.set("location", "Koreatown, Los Angeles");

    window.open(calendarUrl.toString(), "_blank");
  };

  // Share window (Web Share API)
  const shareWindow = async (window: OutreachWindow) => {
    const style = WINDOW_STYLES[window.windowType];
    const shareData = {
      title: `Outreach Window: ${style.label}`,
      text: `${formatTimeRange(window.timeRange)} - ${window.plainLanguageWhy}`,
      url:
        typeof globalThis.window !== "undefined"
          ? globalThis.window.location.href
          : "",
    };

    if (navigator.share && navigator.canShare(shareData)) {
      await navigator.share(shareData);
    } else {
      // Fallback: copy to clipboard
      copyWindowDetails(window);
    }
  };

  return (
    <div className="p-6 space-y-4">
      {/* Header with controls */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-lg font-semibold">Outreach Windows</h2>
          <p className="text-sm text-muted-foreground">
            {windows.length} windows in the planning horizon
          </p>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          {/* Filter Dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm" className="gap-2">
                <Filter className="h-4 w-4" />
                {filterType
                  ? WINDOW_STYLES[filterType as WindowType]?.label || "Filter"
                  : "All Windows"}
                <ChevronDown className="h-3 w-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Filter by Type</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={() => onFilterChange?.(null)}>
                <span className={!filterType ? "font-medium" : ""}>
                  All Windows
                </span>
              </DropdownMenuItem>
              {(Object.keys(WINDOW_STYLES) as WindowType[]).map((type) => {
                const style = WINDOW_STYLES[type];
                const Icon = style.icon;
                return (
                  <DropdownMenuItem
                    key={type}
                    onClick={() => onFilterChange?.(type)}
                  >
                    <Icon className="h-4 w-4 mr-2" />
                    <span className={filterType === type ? "font-medium" : ""}>
                      {style.label}
                    </span>
                  </DropdownMenuItem>
                );
              })}
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Expand/Collapse All */}
          <div className="flex items-center border rounded-md">
            <Button
              variant="ghost"
              size="sm"
              onClick={expandAll}
              className="rounded-r-none border-r"
            >
              <ChevronDown className="h-4 w-4 mr-1" />
              Expand
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={collapseAll}
              className="rounded-l-none"
            >
              <ChevronUp className="h-4 w-4 mr-1" />
              Collapse
            </Button>
          </div>

          {/* Scenario Mode Toggle */}
          <div className="flex items-center gap-2 border rounded-md px-3 py-1.5">
            <Switch
              id="scenario-mode"
              checked={scenarioMode}
              onCheckedChange={onScenarioModeChange}
            />
            <label
              htmlFor="scenario-mode"
              className="text-sm text-muted-foreground cursor-pointer"
            >
              Scenario Mode
            </label>
            {scenarioMode && (
              <Badge
                variant="outline"
                className="text-xs bg-amber-50 dark:bg-amber-950/50"
              >
                Speculative
              </Badge>
            )}
          </div>
        </div>
      </div>

      {/* Scenario Mode Warning */}
      {scenarioMode && (
        <Card className="bg-amber-50 dark:bg-amber-950/30 border-amber-200 dark:border-amber-800">
          <CardContent className="py-3">
            <p className="text-sm">
              <strong>Scenario Mode Active:</strong> Showing speculative
              adjustments for major event planning. Windows are compressed to
              simulate reduced outreach capacity. Use for planning exercises
              only.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Legend */}
      <div className="flex flex-wrap gap-4 text-sm">
        {(Object.keys(WINDOW_STYLES) as WindowType[]).map((type) => {
          const style = WINDOW_STYLES[type];
          const Icon = style.icon;
          const isActive = filterType === type;
          return (
            <button
              key={type}
              onClick={() => onFilterChange?.(isActive ? null : type)}
              className={`
                flex items-center gap-2 px-2 py-1 rounded-md transition-colors
                ${
                  isActive ? "bg-accent ring-1 ring-ring" : "hover:bg-accent/50"
                }
              `}
            >
              <div
                className={`w-4 h-4 rounded ${style.bg} ${style.border} border flex items-center justify-center`}
              >
                <Icon className="h-3 w-3 text-muted-foreground" />
              </div>
              <span className="text-muted-foreground">{style.label}</span>
            </button>
          );
        })}
      </div>

      <Separator />

      {/* Timeline */}
      <div className="space-y-6">
        {Object.entries(windowsByDay).map(([dayKey, dayWindows]) => (
          <div key={dayKey} className="space-y-3">
            {/* Day Header */}
            <div className="sticky top-0 bg-background/95 backdrop-blur-sm py-2 z-10">
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <h3 className="text-sm font-medium">
                  {formatDayHeader(dayKey)}
                </h3>
                <Badge variant="outline" className="text-xs">
                  {dayWindows.length} window{dayWindows.length !== 1 ? "s" : ""}
                </Badge>
              </div>
            </div>

            {/* Windows for this day */}
            <div className="space-y-2 pl-4 border-l-2 border-muted">
              {dayWindows.map((window) => {
                const isExpanded = expandedWindows.has(window.id);
                const isSelected = selectedWindowId === window.id;
                const windowSignals = getWindowSignals(window);
                const style = WINDOW_STYLES[window.windowType];
                const Icon = style.icon;

                return (
                  <Card
                    key={window.id}
                    className={`
                      ${style.bg} ${style.border}
                      ${isSelected ? "ring-2 ring-ring" : ""}
                      transition-all cursor-pointer hover:shadow-md
                    `}
                    onClick={() =>
                      onWindowSelect(isSelected ? undefined : window.id)
                    }
                  >
                    <CardHeader className="py-3 px-4">
                      <div className="flex items-start justify-between gap-2">
                        <div className="space-y-1 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <Icon className="h-4 w-4 text-muted-foreground" />
                            <Badge
                              variant="outline"
                              className="text-xs font-normal"
                            >
                              {formatTimeRange(window.timeRange)}
                            </Badge>
                            <Badge
                              variant={
                                window.windowType === "safer"
                                  ? "default"
                                  : "secondary"
                              }
                              className="text-xs"
                            >
                              {style.label}
                            </Badge>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Badge variant="outline" className="text-xs">
                                  {window.confidenceSummary}
                                </Badge>
                              </TooltipTrigger>
                              <TooltipContent>
                                <p>Data confidence level</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <CardTitle className="text-sm font-medium">
                            {style.description}
                          </CardTitle>
                        </div>
                        <div className="flex items-center gap-1">
                          {/* Quick Actions */}
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  copyWindowDetails(window);
                                }}
                              >
                                <Copy
                                  className={`h-4 w-4 ${
                                    copiedId === window.id
                                      ? "text-green-500"
                                      : ""
                                  }`}
                                />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                              {copiedId === window.id
                                ? "Copied!"
                                : "Copy details"}
                            </TooltipContent>
                          </Tooltip>

                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  addToCalendar(window);
                                }}
                              >
                                <Calendar className="h-4 w-4" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Add to calendar</TooltipContent>
                          </Tooltip>

                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  shareWindow(window);
                                }}
                              >
                                <Share2 className="h-4 w-4" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Share</TooltipContent>
                          </Tooltip>

                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={(e) => {
                              e.stopPropagation();
                              toggleExpanded(window.id);
                            }}
                          >
                            {isExpanded ? (
                              <>
                                <ChevronUp className="h-4 w-4 mr-1" />
                                Less
                              </>
                            ) : (
                              <>
                                <ChevronDown className="h-4 w-4 mr-1" />
                                More
                              </>
                            )}
                          </Button>
                        </div>
                      </div>
                    </CardHeader>

                    {/* Expanded Content */}
                    {isExpanded && (
                      <CardContent className="pt-0 px-4 pb-4 space-y-3">
                        <Separator />

                        {/* Why explanation */}
                        <div>
                          <p className="text-sm text-muted-foreground">
                            {window.plainLanguageWhy}
                          </p>
                        </div>

                        {/* Suggested approach */}
                        <div className="bg-background/50 rounded-md p-3">
                          <p className="text-xs font-medium mb-1">
                            Suggested Approach
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {window.suggestedApproach}
                          </p>
                        </div>

                        {/* Contributing signals */}
                        {windowSignals.length > 0 && (
                          <div>
                            <p className="text-xs font-medium mb-2">
                              Contributing Signals ({windowSignals.length})
                            </p>
                            <div className="space-y-1">
                              {windowSignals.slice(0, 3).map((signal) => (
                                <div
                                  key={signal.id}
                                  className="text-xs text-muted-foreground flex items-center gap-2"
                                >
                                  <Badge
                                    variant="outline"
                                    className="text-xs py-0"
                                  >
                                    {signal.impactLevel}
                                  </Badge>
                                  <span className="truncate">
                                    {signal.description}
                                  </span>
                                </div>
                              ))}
                              {windowSignals.length > 3 && (
                                <p className="text-xs text-muted-foreground">
                                  +{windowSignals.length - 3} more signals
                                </p>
                              )}
                            </div>
                          </div>
                        )}
                      </CardContent>
                    )}
                  </Card>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Empty state */}
      {windows.length === 0 && (
        <Card className="bg-muted/30">
          <CardContent className="py-8 text-center">
            <p className="text-muted-foreground">
              {filterType
                ? `No ${WINDOW_STYLES[
                    filterType as WindowType
                  ]?.label.toLowerCase()} windows found. Try clearing the filter.`
                : "No outreach windows computed for this time period."}
            </p>
            {filterType && (
              <Button
                variant="link"
                onClick={() => onFilterChange?.(null)}
                className="mt-2"
              >
                Clear filter
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* Footer disclaimer */}
      <Card className="bg-muted/30 border-muted">
        <CardContent className="py-3">
          <p className="text-xs text-muted-foreground text-center">
            All windows are derived from simulated, delayed data (24h+). Use for
            planning and coordination, not real-time decisions.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

/**
 * Group windows by day for organized display.
 */
function groupWindowsByDay(
  windows: OutreachWindow[]
): Record<string, OutreachWindow[]> {
  const groups: Record<string, OutreachWindow[]> = {};

  for (const window of windows) {
    const startDate = new Date(window.timeRange.start);
    const dayKey = startDate.toISOString().split("T")[0];

    if (!groups[dayKey]) {
      groups[dayKey] = [];
    }
    groups[dayKey].push(window);
  }

  return groups;
}

/**
 * Format a day key into a human-readable header.
 */
function formatDayHeader(dayKey: string): string {
  const date = new Date(dayKey);
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  if (date.toDateString() === today.toDateString()) {
    return "Today";
  }
  if (date.toDateString() === tomorrow.toDateString()) {
    return "Tomorrow";
  }

  return date.toLocaleDateString("en-US", {
    weekday: "long",
    month: "short",
    day: "numeric",
  });
}

/**
 * Format a time range for display.
 */
function formatTimeRange(timeRange: { start: string; end: string }): string {
  const start = new Date(timeRange.start);
  const end = new Date(timeRange.end);

  const startTime = start.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });
  const endTime = end.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });

  // If same day
  if (start.toDateString() === end.toDateString()) {
    return `${startTime} - ${endTime}`;
  }

  // Multi-day
  return `${startTime} - ${end.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  })} ${endTime}`;
}

/**
 * Format date for Google Calendar URL.
 */
function formatCalendarDate(date: Date): string {
  return date.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
}
